image:
  repository: rdsln/nodejs-app
  tag: latest  # Use a separate image tag for staging

replicaCount: 2  # Medium scaling for staging

database:
  host: mysql-service
  secretName: staging-db-secret  # Staging database secret
  dbname: c3RhZ2luZ2Ri #proddb