image:
  repository: rdsln/nodejs-app
  tag: latest

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

database:
  host: mysql-service
  secretName: ""  # This will be overridden per environment
  

  
