apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: mydockerhub/nodejs-app:latest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
annotations:
  argocd-image-updater.argoproj.io/image-list: mydockerhub/nodejs-app:latest
  argocd-image-updater.argoproj.io/update-strategy: latest
