apiVersion: v1
kind: Secret
metadata:
  name: dev-db-secret
  namespace: nodejs
type: Opaque
data:
  username: cm9vdA==  # base64-encoded "root"
  password: bXktZGV2LXBhc3M=  # base64-encoded "my-dev-pass"
  dbname: GV2ZGI= #devdb
