apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: notification
type: Opaque
stringData:
  slack-webhook: "https://hooks.slack.com/services/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"