apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
type: Opaque
data:
  username: YXJkYXNsYW4=   # Base64-encoded "ardaslan"
  password: Z2hwX283WmdIOVUxSEtLc1JIZXNnRWo1Um9JM0phaHdoTjBVSnZqWA==  # Base64-encoded GitHub PAT
