apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rdsln/nodejs-app:latest
    argocd-image-updater.argoproj.io/rdsln.nodejs-app.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/ardaslan/nodejs-express-mysql.git
    targetRevision: main
    path: helm/nodejs-app
    helm:
      valueFiles:
        - values.yaml
        - values-${ENV}.yaml  # Set ENV as dev, staging, or prod dynamically
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true